<?php

/*
Copyright 2016-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the GNU General Public License as published by the Free Software Foundation,
Version 2.0 (the "License"). You may not use this file except in compliance with the License.
A copy of the License is located in the "license" file accompanying this file.

This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions
and limitations under the License.
*/

include 'aalb_admin_ui_common.php';
$helper = new Aalb_Helper();
$aalb_store_id_names = $helper->get_store_ids_array();
wp_enqueue_script( 'jquery' );
wp_enqueue_script( 'aalb_credentials_js', AALB_CREDENTIALS_JS, array( 'jquery' ), AALB_PLUGIN_CURRENT_VERSION );
wp_localize_script( 'aalb_credentials_js', 'wp_opt', array( 'plugin_url' => AALB_PLUGIN_URL ) );
wp_enqueue_style( 'aalb_credentials_css', AALB_CREDENTIALS_CSS, array(), AALB_PLUGIN_CURRENT_VERSION );
?>

<div class="wrap">
    <h2>Settings for <?= AALB_PROJECT_TITLE ?></h2>
    <br>
    <form method="post" action="options.php">
        <?php settings_fields( AALB_CRED_CONFIG_GROUP );
        do_settings_sections( AALB_CRED_CONFIG_GROUP ); ?>
        <fieldset class="aalb-settings-fieldset">
            <legend class="aalb-settings-legend"> Tracking Id(s) </legend>
            <table class ="widefat fixed aalb-settings-table">
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Associate ID</th>
                    <td class="aalb-settings-input-column">
                    <textarea type="text" id=<?php echo AALB_STORE_ID_NAMES ?> name=<?php echo AALB_STORE_ID_NAMES ?> class="aalb-settings-input-field"
                        value="<?php echo esc_attr( get_option( AALB_STORE_ID_NAMES ) ); ?>"
                        onchange="aalb_credentials_store_ids_onchange(this)"><?php echo esc_attr( get_option( AALB_STORE_ID_NAMES ) ); ?>
                    </textarea>
                    </td>
                    <td>Associate ID is used to monitor traffic and sales from your links to Amazon. You can add one store
                        id or tracking id per row. You are recommended to create a new tracking ID in your Amazon Associates
                        account for using it as Associate ID in the plugin.
                    </td>
                </tr>
            </table>
        </fieldset>
        <br>

        <fieldset class="aalb-settings-fieldset">
            <legend class="aalb-settings-legend">Site Wide Settings</legend>
            <table class ="widefat fixed aalb-settings-table">
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Default Associate ID</th>
                    <td class="aalb-settings-input-column">
                        <?php $default_store_id = get_option( AALB_DEFAULT_STORE_ID, AALB_DEFAULT_STORE_ID_NAME ); ?>
                        <select id=<?php echo AALB_DEFAULT_STORE_ID ?> name=<?php echo AALB_DEFAULT_STORE_ID ?> class="aalb-settings-input-field">
                            <?php
                            foreach ( $aalb_store_id_names as $store_id ) {
                                echo '<option value="' . $store_id . '"';
                                selected( $default_store_id, $store_id );
                                echo '>' . $store_id . '</option>\n';
                            }
                            ?>
                        </select>
                    </td>
                    <td>The Associate ID that will be used for tagging the affiliate links generated by the plugin if no tag
                        is specified in the short code.
                    </td>
                </tr>
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Default Marketplace</th>
                    <td class="aalb-settings-input-column">
                        <?php $default_marketplace = get_option( AALB_DEFAULT_MARKETPLACE, AALB_DEFAULT_MARKETPLACE_NAME ); ?>
                        <select name=<?php echo AALB_DEFAULT_MARKETPLACE ?> class="aalb-settings-input-field">
                            <?php
                            $config_loader = new Aalb_Config_Loader();
                            $aalb_marketplace_names = $config_loader->fetch_marketplaces();
                            foreach ( $aalb_marketplace_names as $marketplace ) {
                                echo '<option value="' . $marketplace . '"';
                                selected( $default_marketplace, $marketplace );
                                echo '>' . $marketplace . '</option>\n';
                            }
                            ?>
                        </select>
                    </td>
                    <td>Set the default Amazon marketplace based on the Amazon website that is identified in your Associates
                        Account (for instance, if you have signed up for Amazon.co.uk site, then your default marketplace
                        selection should be UK).
                    </td>
                </tr>
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Default Template</th>
                    <td class="aalb-settings-input-column">
                        <?php $default_template = get_option( AALB_DEFAULT_TEMPLATE, AALB_DEFAULT_TEMPLATE_NAME ); ?>
                        <select name=<?php echo AALB_DEFAULT_TEMPLATE ?> class="aalb-settings-input-field">
                            <?php
                            $templates = get_option( AALB_TEMPLATE_NAMES, $default_template );
                            foreach ( $templates as $template ) {
                                echo '<option value="' . $template . '"';
                                selected( $default_template, $template );
                                echo '>' . $template . '</option>\n';
                            }
                            ?>
                        </select>
                    </td>
                    <td>The ad template that will be used for rendering the ad if no template is specified in the short
                        code.
                    </td>
                </tr>
                <tr>
                    <td scope="row" colspan="2" class="aalb-settings-no-referrer-column">
                        <input id=<?php echo AALB_NO_REFERRER_DISABLED ?> type="checkbox" name=<?php echo AALB_NO_REFERRER_DISABLED ?> value="true"<?php if (get_option( AALB_NO_REFERRER_DISABLED )) echo "checked='checked'"; ?> />
                        <label class="aalb-settings-no-referrer-text" for="aalb_no_referrer_disabled">Remove rel="noreferrer" for Amazon Affiliate Links from all posts</label>
                    </td>
                    <td> Selecting the checkbox will remove rel="noreferrer" from Amazon links on all posts till date. The action is reversible and you can revert by deselecting the checkbox
                    </td>
                </tr>
            </table>
        </fieldset>
        <br>

        <fieldset class="aalb-settings-fieldset">
            <legend class="aalb-settings-legend">PA-API Credentials</legend>
            <table class ="widefat fixed aalb-settings-table">
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Access Key ID</th>
                    <td class="aalb-settings-input-column">
                        <input type="text" name=<?php echo AALB_AWS_ACCESS_KEY ?> class="aalb-settings-input-field"
                            value="<?php echo esc_attr( openssl_decrypt( base64_decode( get_option( AALB_AWS_ACCESS_KEY ) ), AALB_ENCRYPTION_ALGORITHM, AALB_ENCRYPTION_KEY, 0, AALB_ENCRYPTION_IV ) ); ?>"/>
                    </td>
                    <td>Your Access Key ID that you generated after signing up for the Amazon Product Advertising API. If
                        you have not already signed up for the Amazon Product Advertising API, you can do so by following
                        instructions listed <a
                            href="http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_GettingStarted.html"
                            target="_blank">here</a>.
                    </td>
                </tr>
                <tr>
                    <th scope="row" class="aalb-settings-identifier">Secret Access Key</th>
                    <?php $secret_key = get_option( AALB_AWS_SECRET_KEY );
                    if ( $secret_key ) {
                        $secret_key = AALB_AWS_SECRET_KEY_MASK;
                    }
                    ?>
                    <td class="aalb-settings-input-column"><input type="password" name=<?php echo AALB_AWS_SECRET_KEY ?>
                            class="aalb-settings-input-field" value="<?php echo esc_attr( $secret_key ); ?>"
                            autocomplete="off"/>
                    </td>
                    <td>A key that is used in conjunction with the Access Key ID to cryptographically sign an API request.
                        To retrieve your Access Key ID or Secret Access Key, go to <a
                            href="https://affiliate-program.amazon.com/gp/advertising/api/detail/your-account.html"
                            target="_blank">Manage Your Account</a>. The plugin uses a default encryption key for
                        encrypting the Secret Key. You can change the key using AALB_ENCRYPTION_KEY parameter defined in
                        /aalb_config.php.
                    </td>
                </tr>
            </table>
        </fieldset>

        <div class="aalb-terms-conditions">
            <input id="aalb-terms-checkbox" type="checkbox" name="demo-checkbox" value="1"/>
            <label for="aalb-terms-checkbox">Check here to indicate that you have read and agree to the Amazon Associates Link Builder</label>
            <a href="https://s3.amazonaws.com/aalb-public-resources/documents/AssociatesLinkBuilder-ConditionsOfUse-2017-01-17.pdf"
                target="_blank">Conditions of Use</a>.
        </div>

        <?php submit_button( 'Save Changes', 'primary', 'submit', true, array( 'disabled' => 'disabled' ) ); ?>
    </form>
</div>
